package:
  name: hilltop-py
  version: "1.0.2"

source:
  git_rev: 1.0.2
  git_url: https://github.com/mullenkamp/hilltop-py.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pandas
    - pywin32

test:
  imports:
    - hilltoppy

about:
  home: https://github.com/mullenkamp/hilltop-py
  license: Apache License 2.0
  license_file: LICENSE
